export const SOCKET_CONVERSATION_PATTERN = Object.freeze({
  INIT_CONVERSATION: 'INIT_CONVERSATION',
  DESTROY_CONVERSATION: 'DESTROY_CONVERSATION',
  JOIN_ROOM: 'JOIN_ROOM',
  USER_JOINED: 'USER_JOINED',
  LEAVE_ROOM: 'LEAVE_ROOM',
  USER_LEFT: 'USER_LEFT',
  NEW_CONVERSATION: 'NEW_CONVERSATION',
});
