version: "3"

services:
    postgres:
      container_name: postgres
      restart: always
      image: postgres:13.18
      ports: 
      - '5432:5432'
      volumes:
      - /tmp/data/postgres:/data/postgres
      networks:
        - gateway
        - database_pg
      environment:
        POSTGRES_PASSWORD: 123anh

    # gateway-service:
    #   container_name: gateway-service
    #   ports:
    #     - '3000:3000'
    #   build:
    #     dockerfile: ./apps/gateway/Dockerfile.dev
    #   extends:
    #     file: docker-compose.base.yaml
    #     service: nx-base
    #   restart: on-failure
    #   volumes:
    #     - ./apps/gateway/:/usr/src/root/apps/gateway-service
    #   networks:
    #     - gateway
    #     - database_pg
    #   depends_on:
    #     - postgres

networks:
  gateway: {}
  database_pg: {}